### ISSUE TITLE
Running HARP on a pre-existing audio file doubles speed.

### ISSUE THREAD

**Issue by cwitkowitz** [audacitorch/HARP#65] opened 2023-11-03 16:37 UTC
I've verified this occurs with `cwitkowitz/timbre-trap` and `hugggof/pitch_shifter` after inserting a media file into a track. Both work properly as standalone applications on Hugging Face.

**Comment by bryan-pardo** [comment] 2023-11-16 19:34
Patrick managed to duplicate like this: "I have somehow managed to get a re-pitching glitch by dropping in a file with one sample rate, deleting it from the track, and dropping in another with a different sample rate!"

**Comment by oreillyp** [comment] 2023-11-16 19:35
The issue is probably that HARP is instantiated at one sample rate, but does not update its internal sample rate computations based on the most recent state of the audio region

**Comment by xribene** [comment] 2023-11-30 17:48
This issue didn't have to do with dropping files of different sampling rate in sequence. Every file with different sampling rate from the DAW's had the same problem. Even though this issue looks like the previous sampling rate problems we had in tensorjuce, the root cause is different, and stems from the fact that no sampling-rate conversion happens in the neural-model side (as we did with the local torch models). 
The bug is fixed in the "windowsBuild" branch, but I'll push it also in branch "cb/issue-65" so it can be merged into the main.

**Closed** 2023-12-04 21:06 UTC
Labels: neurips
